version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_social_postgres
    environment:
      POSTGRES_DB: ai_social_support
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/models/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: ai_social_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai_social_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis123
    restart: unless-stopped

  # Optional: MongoDB for additional document storage
  mongodb:
    image: mongo:7
    container_name: ai_social_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
  mongodb_data: